Vagrant.configure("2") do |config|
  config.vm.box = "felipemedeiros/focal"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 3306, host: 3306, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "./www", "/var/www/html"
  config.vm.provision "shell", path: "provisionamento.sh"  
end